name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  build-foo:
    name: build foo
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building foo..."

  build-bar:
    if: false
    name: build bar
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building bar..."

  build-baz:
    name: build baz
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "Failing baz..." && exit 1

  deploy:
    if: |
      always() &&
      contains(needs.*.result, fromJSON('["success", "skipped"]'))
    needs:
    - build-foo
    - build-bar
    - build-baz
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "deploying..."
    - run: |
        cat > values.yaml <<EOF
        foo:
          bar: baz
        github:
          run_id: ""
        EOF
    - uses: mikefarah/yq@v4
      with:
        cmd: yq -i '.github.run_id = "${{ github.run_id }}"' values.yaml
    - run: cat values.yaml

  debug:
    if: always()
    needs:
      - build-foo
      - build-bar
    name: debug
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat <<EOF
          contains(fromJSON('["success", "skipped"]'), needs.*.result)
        EOF
    - run: |
        cat <<EOF
          contains(needs.*.result, fromJSON('["success", "skipped"]'))
        EOF
    - run: |
        cat <<EOF
          always() &&
          contains(needs.*.result, fromJSON('["success", "skipped"]'))
        EOF
