name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  release:
    types:
      - published
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  Build:
    uses: ./.github/workflows/reusable.yml
