name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  build-foo:
    name: build foo
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building foo..."

  build-bar:
    if: false
    name: build bar
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building bar..."

  build-baz:
    name: build baz
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building baz..."

  deploy:
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    needs:
    - build-foo
    - build-bar
    - build-baz
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "deploying..."
    - uses: mikefarah/yq@main
      with:
        cmd: yq -i '.github.run_id = "${{ github.run_id }}"' values.yaml
    - run: cat values.yaml

  debug:
    if: always()
    needs:
      - build-foo
      - build-bar
    name: debug
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat <<EOF
          ${{ !contains(needs.*.result, 'failure') &&
          !contains(needs.*.result, 'cancelled') }}
        EOF
