name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Building..."
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - dev
          - prod
    environment: ${{ matrix.env }}
    steps:
      - run: |
          echo "Deploying to ${{ matrix.env }}..."
      - run: |
          echo "Deployed to ${{ matrix.env }}..."
