name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  build-foo:
    name: build foo
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building foo..."

  build-bar:
    name: build bar
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building bar..."

  build-baz:
    if: false
    name: build baz
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building baz..."

  deploy:
    if: needs.build-bar.result == ('success' || 'skipped')
    needs:
    - build-foo
    - build-bar
    - build-baz
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "deploying..."
