name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  release:
    types:
      - published
      - created
      - edited

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:

      - name: Print event name
        run: |
          echo "github.event_name: ${{ github.event_name }}"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: hello-ci
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,event=branch,prefix={{branch}}-,enable=${{ github.event_name == 'push' }}
