name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  release:
    types:
      - published
      - created
      - edited

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      dockerfile: ${{ steps.filter.outputs.dockerfile }}
      readme: ${{ steps.filter.outputs.readme }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dockerfile:
              - Dockerfile
            readme:
              - README.md

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.dockerfile == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hello-ci

      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
