name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - dev
          - prod
    environment: ${{ matrix.env }}
    steps:
      - run: |
          echo "Deploying to ${{ matrix.env }}..."
