name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  build-foo:
    name: build foo
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building foo..."

  build-bar:
    if: false
    name: build bar
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "building bar..."

  build-baz:
    name: build baz
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "Failing baz..." && exit 1

  deploy:
    if: |
      contains(fromJSON('["success", "skipped"]'), needs.build-foo.result) &&
      contains(fromJSON('["success", "skipped"]'), needs.build-bar.result) &&
      contains(fromJSON('["success", "skipped"]'), needs.build-baz.result) &&
      always()
    needs:
    - build-foo
    - build-bar
    - build-baz
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - run: printf '%s\n' "deploying..."

  debug:
    if: ${{ always() }}
    needs:
      - build-foo
      - build-bar
    name: debug
    runs-on: ubuntu-latest
    steps:
    - run: |
        cat <<EOF
          ${{ contains(fromJSON('["success", "skipped"]'), needs.build-foo.result) }}
        EOF
    - run: |
        cat <<EOF
          ${{ contains(fromJSON('["success", "skipped"]'), needs.build-bar.result) }}
        EOF
    - run: |
        cat <<EOF
          ${{ contains(fromJSON('["success", "skipped"]'), needs.build-foo.result) &&
              contains(fromJSON('["success", "skipped"]'), needs.build-bar.result)
          }}
        EOF
    - run: |
        cat <<EOF
          ${{ needs.build-bar.result == 'success' || needs.build-bar.result == 'skipped' }}
        EOF
