name: CI

on:
  pull_request:
  push:
  release:
    types:
    - published
    - created
    - edited

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.github.run_id = "${{ github.run_id }}"' values.yaml
    - run: cat values.yaml
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Update run id image to ${{ github.run_id }}'
