name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  release:
    types:
      - published
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/reusable.yml
    with:
      component: backend
  frontend:
    name: Frontend
    uses: ./.github/workflows/reusable.yml
    with:
      component: frontend
