name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - qa
  release:
    types:
      - published
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:

      - run: |
          echo "github.workflow: ${{ github.workflow }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.run_id: ${{ github.run_id }}"
